### ISSUE TITLE
Syntaxerror in TextInput tests

### ISSUE THREAD

**Issue by mvaerle** [export-mike/react-redux-boilerplate#2]
Thanks for providing this example boilerplate. Just did a fresh clone of the repository and I'm getting a SyntaxError on line 14 in src/components/TextInput/test/index-test.js and line 15 in src/components/PrimaryTextInput/test/index-test.js.

It looks like the JSX tag in the preceding line is not being closed correctly. Once I changed that the tests failed because change isn't called. I changed the simulate call to the following:

`wrapper.find(TextInput).simulate('change', {target: {value: 'a'}});`

I don't know if this is the correct fix, and why the change handler isn't called as a result of the keydown. Also see: https://github.com/airbnb/enzyme/issues/76

**Comment by export-mike** [comment]
fixed in v1.0.2, thanks for taking the time to try out my boilerplate and submit the issue. I'm planning to update this and make a v2 which will have some rather large changes to async stuff but mostly updating dependencies etc
