### ISSUE TITLE
Use browserHistory and syncHistoryWithStore?

### ISSUE THREAD

**Issue by ghost** [export-mike/react-redux-boilerplate#3]
I am using this excellent boilerplate and have learnt a lot from it. Once feature I would like to see is to replace hashHistory with browserHistory and syncHistoryWithStore. Or would that mean evergreen browsers only?

**Comment by export-mike** [comment]
Hey thanks!

by all means do that, you'll need to configure routing back to index.html
in express too

This boilerplate had deployment to the likes of s3 and surge in mind which
do not appear to support redirect to index.html hence hashHistory

Take a look at some of the config in express and routes of this
experimental repo I have been using
https://github.com/export-mike/react-hot-boilerplate/blob/master/server.production.js

https://github.com/export-mike/react-hot-boilerplate/blob/master/src/Routes.js

I'm moving away from this repo to what's in my fork of
react-hot-boilerplate, with styling done by radium and side effects being
managed by redux-saga.
